sudo: required

language: ruby

rvm:
  - 2.2.3

git:
  depth: 25

services:
  - docker

before_install:
  - docker build -t rmarchei/jenkins .

script:
  - docker run --rm rmarchei/jenkins java -version
  - docker run --rm rmarchei/jenkins mvn -version
